version: '3.8'

services:
  frontend:
    image: devsecopsuc/frontend-web:v9
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - auth
      - rooms

  auth:
    image: devsecopsuc/auth-service:v3
    restart: always

  rooms:
    image: devsecopsuc/rooms-service:v3
    restart: always
