services:
  auth:
    image: devsecopsuc2025/auth-service:v1
    restart: always

  rooms:
    image: devsecopsuc2025/rooms-service:v1
    restart: always

  frontend:
    image: devsecopsuc2025/frontend-web:v1
    ports:
      - "8080:80"
    depends_on:
      - auth
      - rooms
    restart: always
